### ISSUE TITLE
Workflow examples and some general points of interest

### ISSUE THREAD

**Issue by LinguList** [cysouw/qlcPipe#1]
I didn't want to make a PR, so I just make an issue here to bring up some points I find useful mentioning.

I like this idea very much, and think it's time that people share their pipelines along with their source code. I recently have tried to provide make files in a couple of publications, but also some examples for LingPy usage, most of them stored as  [github gist](http://gist.github.com) and can be found [here](https://gist.github.com/lingulist). 

What is great about github-gist is that it offers even a possibility to upload content anonymously (simply upload without logging in!), which is excellent for submitting publications to anonymous reviewers.

**Comment by cysouw** [comment]
The point of the current repository is not simply to collect different pipelines from different people, but to provide a way to combine parts of pipelines from different people together into new pipelines. The hope is that it might be possible at some stage to take, say, some aspects of lingpy in python, with some aspects of qlcMatrix in R, with some basic C++ parts (etc., you get the point) and combine them without needing to dive deep into the structure of the foreign code.

Another way to look at it is to make simple interfaces available of methods that might be of interest to others.

For further discussion, let's not use the issues tracker, but maybe email, or the github wiki. I'll close this issue
