### ISSUE TITLE
Spec and catalog instead of collection of wrappers

### ISSUE THREAD

**Issue by xrotwang** [cysouw/qlcPipe#2]
While I think it's good to curate a catalog of linguistic software which can be used in pipelines, trying to curate a set of wrappers seems to be a bit too much work to scale. E.g. LingPy should rather try to provide [UNIX commands](https://github.com/lingpy/lingpy/issues/176) out of the box, i.e. installed into the user's system upon installation of LingPy. If wrappers are curated separate from the functionality they wrap, there would have to be ways to
- declare dependencies, including versions,
- install the wrappers into a UNIX system.

So maybe this repository should try to specify what is expected of a pipeline-able command, and maybe give some examples; but the mid-term goal should be to have developers of the underlying linguistic software provide these commands together with their software.

**Comment by cysouw** [comment]
I completely agree! yes, that is what I have in mind too. I will make it clearer in the README.
