### ISSUE TITLE
Tie discussion of pipeline to discussion of formats

### ISSUE THREAD

**Issue by xrotwang** [cysouw/qlcPipe#3]
I think this pipeline idea could be one of the big selling points of data formats like [cldf](https://github.com/glottobank/cldf), and at the same time it does rely to some extent on the existence of such formats. So I would propose to tie the discussion of both together, e.g. [here](https://github.com/glottobank/cldf/blob/master/bigger_picture.md).

**Comment by cysouw** [comment]
added link to readme
