### ISSUE TITLE
Install exec with R

### ISSUE THREAD

**Issue by cysouw** [cysouw/qlcPipe#4]
I could not find any way to automatically link exec with R packages. This is the current situations:
- you can add scripts to a folder "exec" inside an R package, and such scripts will be made executable on install.
- however: this mechanism is intended for internal usage in the package, not for usage outside of the package. So, the executable is not automatically linked to PATH.
- it would be ideal if such executables are linked to PATH on install, so a user just has to install the package, and then can use the executable from the command line, but I don't know how to do this (I search a lot online, but to no avail).

As a test, I have added an executable to one of my R-packages. To install it from github do the following:
- install R from https://cran.r-project.org
- within R (you can start R from the command line as "R") install the following:

```
# help functions to install directly from github
install.packages("devtools")
# get the most recent version from github, all necessary dependencies should be automatically installed as well
devtools::github_install("cysouw/qlcMatrix")
```

if you then go to the precise directory, you can use the executable, try this on the command line:

```
cd /Library/Frameworks/R.framework/Resources/library/qlcMatrix/exec/
sim.strings.R --help
```

@xrotwang : do you have any suggestions how to automatically link this executable to PATH on installing  the library? I know you are no R-specialist, but maybe you have any suggestions :-)

**Comment by xrotwang** [comment]
I think this behaviour of R packages upon installation can be regarded as a feature, too; in particular in the absence of a mechanism like [python's virtualenvs](https://virtualenv.readthedocs.org/en/latest/). You would not want to shadow an existing command just because some R package came with a script with the same name.

So I guess adding info to the README explaining how to add the `exec` directory to your `PATH` (for Linux, Mac and Windows) is the best you can do.

**Comment by cysouw** [comment]
But then we have to hope for everybody to do all that hassle, and I'm sure nobody would do it. So, although I agree with you that the executables should be distributed with the code itself, it still seems to be worthwhile to have a project (like this one) with the following model:
- we collect executables from various backgrounds
- describe what people will have to do to get them running
- ideally, we might offer some kind of makefile to have everything be done in one go

Remains a hassle, <sigh>

**Comment by cysouw** [comment]
@xrotwang do you have some description how the such files are added to you path on linux and/or windows?

**Comment by xrotwang** [comment]
Here's [OSX 10.11](http://coolestguidesontheplanet.com/add-shell-path-osx/), here's [Linux (with bash)](http://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path).
